// Auto-generated from Saveetha Engineering College R2024 Curriculum
// All departments: MECH, ECE, EEE, Civil, BME, IT, CSE, CSE(IoT), CSE(CS), AIML, AIDS

export interface SubjectSuggestion {
  name: string;
  theory: number;
  practical: number;
}

export const SUBJECTS_DB: SubjectSuggestion[] = [
  {"name":"English for Engineers","theory":3,"practical":1},
  {"name":"Technical Writing and Presentation","theory":0,"practical":2},
  {"name":"Human Values and Professional Ethics","theory":2,"practical":0},
  {"name":"Heritage of Tamils","theory":1,"practical":0},
  {"name":"Tamils and Technology","theory":1,"practical":0},
  {"name":"Environmental Sciences and Sustainability","theory":2,"practical":0},
  {"name":"Calculus and Matrix Algebra","theory":4,"practical":0},
  {"name":"Statistics and Numerical Methods","theory":3,"practical":1},
  {"name":"Transforms and Differential Equations","theory":4,"practical":0},
  {"name":"Basics of Engineering Physics","theory":3,"practical":0},
  {"name":"Materials Science","theory":3,"practical":1},
  {"name":"Basic Engineering Chemistry","theory":3,"practical":1},
  {"name":"Python Programming","theory":2,"practical":1},
  {"name":"Artificial Intelligence and Applications","theory":1,"practical":2},
  {"name":"Engineering Drawing and Visualisation","theory":3,"practical":1},
  {"name":"Engineering Practices Lab","theory":0,"practical":1},
  {"name":"Engineering Mechanics","theory":4,"practical":0},
  {"name":"Mechanics of Solids","theory":3,"practical":1},
  {"name":"Fluid Mechanics and Machinery","theory":3,"practical":1},
  {"name":"Basic Electrical, Electronics and Instrumentation Engineering","theory":2,"practical":1},
  {"name":"Electrical Drives and Control","theory":3,"practical":0},
  {"name":"Engineering Thermodynamics for Mechanical Engineers","theory":4,"practical":0},
  {"name":"Thermal Engineering","theory":3,"practical":1},
  {"name":"Heat and Mass Transfer","theory":4,"practical":1},
  {"name":"Power Generation Engineering","theory":4,"practical":0},
  {"name":"Manufacturing Technology I","theory":3,"practical":1},
  {"name":"Manufacturing Technology II","theory":3,"practical":1},
  {"name":"Theory of Machines","theory":3,"practical":1},
  {"name":"Design of Machine Elements","theory":3,"practical":1},
  {"name":"Metrology and Measurements","theory":3,"practical":1},
  {"name":"Hydraulics and Pneumatics","theory":3,"practical":0},
  {"name":"Mechatronics and IoT","theory":3,"practical":1},
  {"name":"CAD/CAM","theory":2,"practical":1},
  {"name":"Finite Element Analysis","theory":4,"practical":1},
  {"name":"Introduction to Machine Learning","theory":2,"practical":1},
  {"name":"Fundamentals of 3D Printing Technologies","theory":3,"practical":0},
  {"name":"Reverse Engineering and CAD Modelling","theory":3,"practical":1},
  {"name":"Design for 3D Printing","theory":3,"practical":1},
  {"name":"3D Printing Machines and Systems","theory":3,"practical":0},
  {"name":"Materials for 3D Printing","theory":3,"practical":0},
  {"name":"3D Printing for Medical Applications","theory":3,"practical":1},
  {"name":"Hybrid and Electric Vehicle Technology","theory":3,"practical":0},
  {"name":"Automotive Materials, Components, Design and Testing","theory":2,"practical":1},
  {"name":"Smart Mobility and Intelligent Vehicles","theory":3,"practical":0},
  {"name":"CAE and CFD Approach in Future Mobility","theory":2,"practical":1},
  {"name":"Thermal Management of Batteries","theory":3,"practical":0},
  {"name":"Vehicle Health Monitoring, Maintenance and Safety","theory":3,"practical":0},
  {"name":"Value Engineering","theory":3,"practical":0},
  {"name":"Computer Integrated Manufacturing Systems","theory":2,"practical":1},
  {"name":"Design For X","theory":3,"practical":0},
  {"name":"Product Life Cycle Management","theory":3,"practical":0},
  {"name":"Ergonomics in Design","theory":3,"practical":0},
  {"name":"New Product Development","theory":3,"practical":0},
  {"name":"Digital Manufacturing and IoT","theory":2,"practical":1},
  {"name":"Lean Manufacturing","theory":3,"practical":0},
  {"name":"Modern Robotics","theory":2,"practical":1},
  {"name":"Green Manufacturing Design and Practices","theory":3,"practical":0},
  {"name":"Environment Sustainability and Impact Assessment","theory":3,"practical":0},
  {"name":"Energy Saving Machinery and Components","theory":3,"practical":0},
  {"name":"Optimization Techniques","theory":4,"practical":0},
  {"name":"Statistical Quality Control","theory":4,"practical":0},
  {"name":"Quality Audit System","theory":3,"practical":0},
  {"name":"Operations and Inventory Management","theory":3,"practical":0},
  {"name":"Reliability Engineering","theory":3,"practical":0},
  {"name":"Discrete Event System Simulation","theory":3,"practical":0},
  {"name":"Automotive Engineering","theory":3,"practical":0},
  {"name":"Refrigeration And Air Conditioning Technology","theory":3,"practical":0},
  {"name":"Turbo Machines","theory":3,"practical":0},
  {"name":"Gas Dynamics and Jet Propulsion","theory":3,"practical":0},
  {"name":"Advanced Internal Combustion Engine Technology","theory":3,"practical":0},
  {"name":"Computational Fluid Dynamics and Heat Transfer","theory":3,"practical":0},
  {"name":"3D Printing Processes","theory":3,"practical":1},
  {"name":"Composite Materials Engineering","theory":3,"practical":0},
  {"name":"Non Conventional Machining Processes","theory":3,"practical":0},
  {"name":"Design of Transmission System","theory":3,"practical":0},
  {"name":"Process Planning and Cost Estimation","theory":2,"practical":1},
  {"name":"Intellectual Property Rights","theory":2,"practical":1},
  {"name":"Machine Learning Applications in Mechanical Engineering","theory":3,"practical":1},
  {"name":"Advanced Solid Surface Design and Simulation Technique","theory":0,"practical":3},
  {"name":"Organizational Behavior and Leadership","theory":3,"practical":0},
  {"name":"Physics for Electronics Engineering","theory":3,"practical":1},
  {"name":"Chemistry of Engineering Materials","theory":2,"practical":1},
  {"name":"Linear Algebra and Probability","theory":4,"practical":0},
  {"name":"Electric Circuits and Networks","theory":3,"practical":1},
  {"name":"Fundamentals of C Programming","theory":2,"practical":1},
  {"name":"Advanced C Programming","theory":2,"practical":1},
  {"name":"Data Structures","theory":2,"practical":1},
  {"name":"Object Oriented Programming using C++","theory":2,"practical":1},
  {"name":"Object Oriented Programming using Java","theory":2,"practical":1},
  {"name":"Electronic Devices","theory":3,"practical":1},
  {"name":"Signals and Systems","theory":3,"practical":0},
  {"name":"Digital Logic Circuits Design","theory":3,"practical":1},
  {"name":"Electronic Circuits","theory":3,"practical":1},
  {"name":"Electromagnetic Theory and Transmission Lines","theory":4,"practical":0},
  {"name":"Analysis and Design of Analog ICs","theory":3,"practical":1},
  {"name":"Microprocessor and Microcontroller","theory":3,"practical":1},
  {"name":"Analog Communication","theory":3,"practical":1},
  {"name":"Digital Communication","theory":3,"practical":1},
  {"name":"Discrete Time Signal Processing","theory":3,"practical":1},
  {"name":"VLSI Design","theory":3,"practical":1},
  {"name":"Wireless Communication","theory":3,"practical":0},
  {"name":"Embedded Systems and IoT","theory":2,"practical":1},
  {"name":"Control System Engineering","theory":3,"practical":0},
  {"name":"Optical Communication and Network","theory":2,"practical":1},
  {"name":"Communication Networks and Cyber Security","theory":2,"practical":1},
  {"name":"Antennas and Microwave Engineering","theory":3,"practical":1},
  {"name":"Introduction to MEMS and NEMS","theory":3,"practical":0},
  {"name":"Verilog HDL","theory":2,"practical":1},
  {"name":"System Verilog for Design and Verification","theory":2,"practical":1},
  {"name":"Physical Design for VLSI","theory":2,"practical":1},
  {"name":"VLSI Technology","theory":3,"practical":0},
  {"name":"Low Power VLSI Design","theory":3,"practical":0},
  {"name":"Testing of VLSI Circuits","theory":3,"practical":0},
  {"name":"Natural Language Processing","theory":3,"practical":0},
  {"name":"Digital Image Processing","theory":3,"practical":0},
  {"name":"Computer Vision and Pattern Recognition","theory":3,"practical":0},
  {"name":"Software Defined Networks","theory":2,"practical":1},
  {"name":"Wireless Sensor Network Design","theory":3,"practical":0},
  {"name":"Data Storage Technologies","theory":3,"practical":0},
  {"name":"DSP Processors","theory":3,"practical":0},
  {"name":"Software for Embedded System","theory":3,"practical":0},
  {"name":"Real Time Operating Systems","theory":3,"practical":0},
  {"name":"Automotive Embedded Systems","theory":3,"practical":0},
  {"name":"IoT Processors","theory":2,"practical":1},
  {"name":"IoT Based System Design","theory":3,"practical":0},
  {"name":"5G Communication and Networks","theory":2,"practical":1},
  {"name":"5G Edge and Cloud Computing","theory":2,"practical":1},
  {"name":"5G Blockchains and Security","theory":3,"practical":0},
  {"name":"Smart Healthcare Systems","theory":3,"practical":0},
  {"name":"AR and VR for 5G","theory":2,"practical":1},
  {"name":"6G Communication Technologies","theory":3,"practical":0},
  {"name":"Satellite Communication","theory":3,"practical":0},
  {"name":"MEMS Fabrication and Integration","theory":2,"practical":1},
  {"name":"FEA and MEMS Simulation","theory":2,"practical":1},
  {"name":"RF MEMS and MOEMS","theory":2,"practical":1},
  {"name":"BioMEMS and Microfluidics","theory":2,"practical":1},
  {"name":"Nanoscience and Nano Technology","theory":2,"practical":1},
  {"name":"Design, Testability and Applications of MEMS and NEMS","theory":3,"practical":0},
  {"name":"Analysis of Algorithms","theory":2,"practical":1},
  {"name":"Database Management System and its Applications","theory":3,"practical":1},
  {"name":"Graph Theory and Applications","theory":3,"practical":0},
  {"name":"Embedded Board Design","theory":2,"practical":1},
  {"name":"Embedded Board Manufacturing","theory":2,"practical":1},
  {"name":"Electromagnetic Theory","theory":3,"practical":0},
  {"name":"Transformers and DC Machines","theory":3,"practical":1},
  {"name":"AC Machines","theory":3,"practical":1},
  {"name":"Digital Electronics","theory":3,"practical":1},
  {"name":"Measurement and Instrumentation Systems","theory":2,"practical":1},
  {"name":"Linear Integrated Circuits and Applications","theory":3,"practical":1},
  {"name":"Control Systems","theory":2,"practical":1},
  {"name":"Electrical Power Transmission and Distribution Systems","theory":3,"practical":0},
  {"name":"Power System Analysis","theory":3,"practical":1},
  {"name":"Power Electronics","theory":3,"practical":1},
  {"name":"Microprocessor and Microcontroller Systems","theory":2,"practical":1},
  {"name":"Solid State Drives and Control","theory":2,"practical":1},
  {"name":"Digital Signal Processing","theory":3,"practical":1},
  {"name":"High Voltage Engineering","theory":3,"practical":0},
  {"name":"Fundamentals of Renewable Energy Systems","theory":2,"practical":1},
  {"name":"Restructured Power Systems","theory":3,"practical":0},
  {"name":"Flexible AC Transmission Systems","theory":3,"practical":0},
  {"name":"Energy Storage Technologies","theory":3,"practical":0},
  {"name":"Power Quality","theory":3,"practical":0},
  {"name":"Microgrid Modelling and Analysis","theory":3,"practical":0},
  {"name":"Microgrid Protection and Control","theory":3,"practical":0},
  {"name":"Wind Energy and Sustainability","theory":2,"practical":1},
  {"name":"Smart Grid Technology for Renewable Energy System","theory":2,"practical":1},
  {"name":"Grid Connected and Standalone PV Solar Plant Design","theory":2,"practical":1},
  {"name":"Energy Forecasting and Modelling","theory":3,"practical":0},
  {"name":"Solar Energy Engineering and Technology","theory":3,"practical":0},
  {"name":"Power Electronics for Renewable Energy Systems","theory":2,"practical":1},
  {"name":"Embedded System Design","theory":2,"practical":1},
  {"name":"Embedded Control for Electric Drives","theory":2,"practical":1},
  {"name":"Embedded System for Automotive Applications","theory":2,"practical":1},
  {"name":"Embedded Processors","theory":2,"practical":1},
  {"name":"Embedded C Programming","theory":2,"practical":1},
  {"name":"Smart System Automation","theory":3,"practical":0},
  {"name":"Introduction to Fundamentals of Electric Vehicles","theory":3,"practical":0},
  {"name":"Electric Vehicle Powertrain and Integration","theory":2,"practical":1},
  {"name":"Electric Vehicle Charging Infrastructure","theory":3,"practical":0},
  {"name":"Electric Vehicle Grid Integration","theory":2,"practical":1},
  {"name":"Embedded IoT for Electric Vehicles","theory":2,"practical":1},
  {"name":"Embedded AI for Electric Vehicles","theory":2,"practical":1},
  {"name":"Battery Technologies and Management Systems for Electric Vehicles","theory":3,"practical":0},
  {"name":"Power System Transients","theory":3,"practical":0},
  {"name":"Protection and Switchgear","theory":3,"practical":0},
  {"name":"Utilisation, Safety and Maintenance of Electrical Systems","theory":3,"practical":0},
  {"name":"Substation Engineering and Automation","theory":3,"practical":0},
  {"name":"Sustainable Engineering Design for Indoor And Outdoor Illumination","theory":2,"practical":1},
  {"name":"Energy Management and Auditing","theory":3,"practical":0},
  {"name":"Computer Aided Design of Electrical Machines","theory":2,"practical":1},
  {"name":"Soft Computing Techniques","theory":3,"practical":0},
  {"name":"Physics for Civil Engineering","theory":3,"practical":1},
  {"name":"Engineering Graphics","theory":3,"practical":0},
  {"name":"Engineering Practices Laboratory","theory":0,"practical":2},
  {"name":"Fluid Mechanics","theory":3,"practical":1},
  {"name":"Construction Materials and Technology","theory":2,"practical":1},
  {"name":"Engineering Geology","theory":2,"practical":1},
  {"name":"Mechanics of Materials","theory":3,"practical":1},
  {"name":"Surveying","theory":3,"practical":1},
  {"name":"Soil Mechanics","theory":3,"practical":1},
  {"name":"Applied Hydraulic Engineering","theory":2,"practical":1},
  {"name":"Concrete Technology","theory":3,"practical":1},
  {"name":"Structural Analysis","theory":3,"practical":0},
  {"name":"Transportation Engineering","theory":2,"practical":1},
  {"name":"Environmental Engineering","theory":3,"practical":0},
  {"name":"Water and Wastewater Analysis Laboratory","theory":0,"practical":2},
  {"name":"Foundation Engineering","theory":3,"practical":0},
  {"name":"Water Resources Engineering","theory":3,"practical":0},
  {"name":"Design of Reinforced Concrete Elements","theory":3,"practical":0},
  {"name":"Survey Camp","theory":0,"practical":2},
  {"name":"Advanced Structural Analysis","theory":3,"practical":0},
  {"name":"Design of Steel Structures","theory":3,"practical":0},
  {"name":"Estimation, Costing and Valuation","theory":3,"practical":0},
  {"name":"Building Information and Modeling","theory":0,"practical":3},
  {"name":"Computer Aided Plumbing Drawing","theory":0,"practical":2},
  {"name":"Prestressed Concrete Structures","theory":3,"practical":0},
  {"name":"Robotics and Automation in Construction","theory":2,"practical":0},
  {"name":"Advanced Material Science and 3D Printing","theory":2,"practical":0},
  {"name":"Design Studio and Detailing","theory":1,"practical":2},
  {"name":"Advanced Mechanics of Materials","theory":3,"practical":0},
  {"name":"Industrial Structures","theory":3,"practical":0},
  {"name":"Structural Dynamics and Earthquake Engineering","theory":3,"practical":0},
  {"name":"Bridge Engineering","theory":3,"practical":0},
  {"name":"Rehabilitation and Heritage Restoration","theory":3,"practical":0},
  {"name":"Irrigation Engineering and Drawing","theory":3,"practical":0},
  {"name":"Groundwater Engineering","theory":3,"practical":0},
  {"name":"Integrated Water Resources Management","theory":3,"practical":0},
  {"name":"Water Resources Systems","theory":3,"practical":0},
  {"name":"Advanced Hydrology and Flood Risk Management","theory":3,"practical":0},
  {"name":"Hydraulic Modeling and Water Infrastructure Simulation","theory":3,"practical":0},
  {"name":"Geo-Environmental Engineering","theory":3,"practical":0},
  {"name":"Ground Improvement Techniques","theory":3,"practical":0},
  {"name":"Soil Dynamics and Machine Foundations","theory":3,"practical":0},
  {"name":"Rock Mechanics and Tunneling Technology","theory":3,"practical":0},
  {"name":"Geosynthetics and Reinforced Soil Structures","theory":3,"practical":0},
  {"name":"Slope Stability and Landslide Management","theory":3,"practical":0},
  {"name":"Geoinformatics Applications","theory":3,"practical":0},
  {"name":"Geographical Information System","theory":3,"practical":0},
  {"name":"Digital Cadastre","theory":3,"practical":0},
  {"name":"Remote Sensing and Image Processing","theory":3,"practical":0},
  {"name":"Hydrographic Surveying","theory":3,"practical":0},
  {"name":"Photogrammetry","theory":3,"practical":0},
  {"name":"Industrial Wastewater Management","theory":3,"practical":0},
  {"name":"Environmental Quality Monitoring","theory":3,"practical":0},
  {"name":"Environmental Impact Assessment","theory":3,"practical":0},
  {"name":"Air Pollution Engineering","theory":3,"practical":0},
  {"name":"Data Analytics in Environmental Engineering","theory":3,"practical":0},
  {"name":"Instrumentation for Pollution Monitoring and Management","theory":3,"practical":0},
  {"name":"Airport Engineering","theory":3,"practical":0},
  {"name":"Traffic Engineering and Management","theory":3,"practical":0},
  {"name":"Port and Harbour Engineering","theory":3,"practical":0},
  {"name":"Railway Engineering","theory":3,"practical":0},
  {"name":"Pavement Engineering","theory":3,"practical":0},
  {"name":"Transportation Planning Process","theory":3,"practical":0},
  {"name":"Sustainable Construction and Lean Construction","theory":3,"practical":0},
  {"name":"Formwork Engineering","theory":3,"practical":0},
  {"name":"Construction Engineering and Occupational Safety","theory":3,"practical":0},
  {"name":"Contract Laws and Regulations","theory":3,"practical":0},
  {"name":"Construction Project Management","theory":3,"practical":0},
  {"name":"Material Science and Engineering","theory":3,"practical":0},
  {"name":"Prefabricated Structures","theory":3,"practical":0},
  {"name":"Watershed Conservation and Management","theory":3,"practical":0},
  {"name":"Analysis and Design of Deep Foundations","theory":3,"practical":0},
  {"name":"UAV and Drone Technology for Mapping","theory":3,"practical":0},
  {"name":"Solid and Hazardous Waste Management","theory":3,"practical":0},
  {"name":"Intelligent Transport Systems","theory":3,"practical":0},
  {"name":"Advanced Construction Techniques","theory":3,"practical":0},
  {"name":"Precast Technology","theory":3,"practical":0},
  {"name":"Urban Water Infrastructure","theory":3,"practical":0},
  {"name":"Tunneling Engineering","theory":3,"practical":0},
  {"name":"Spatial Data Infrastructure and Management","theory":3,"practical":0},
  {"name":"Water Quality and Management","theory":3,"practical":0},
  {"name":"Urban Infrastructure and Smart Cities","theory":3,"practical":0},
  {"name":"Construction Equipment and Machinery","theory":3,"practical":0},
  {"name":"Chemistry for Biomedical Engineering","theory":2,"practical":1},
  {"name":"Anatomy and Human Physiology","theory":3,"practical":0},
  {"name":"Electronic Circuits and Special Devices","theory":2,"practical":1},
  {"name":"Analog and Digital Integrated Circuits","theory":3,"practical":0},
  {"name":"Integrated Circuits laboratory","theory":0,"practical":1},
  {"name":"Basics of Signals and Systems","theory":3,"practical":0},
  {"name":"Biochemistry","theory":3,"practical":1},
  {"name":"Biomedical Instrumentation","theory":3,"practical":1},
  {"name":"Clinical Instrumentation","theory":3,"practical":1},
  {"name":"Medical Imaging System I","theory":3,"practical":0},
  {"name":"Medical Imaging System II","theory":3,"practical":0},
  {"name":"Pathology and Microbiology","theory":3,"practical":1},
  {"name":"Clinical Laboratory Equipment and Techniques","theory":2,"practical":1},
  {"name":"Therapeutic Equipments I","theory":3,"practical":1},
  {"name":"Therapeutic Equipments II","theory":3,"practical":1},
  {"name":"Lasers in Healthcare Applications","theory":3,"practical":0},
  {"name":"Bio Materials and Artificial Organs","theory":3,"practical":0},
  {"name":"Biomedical Signal Processing","theory":3,"practical":1},
  {"name":"Medical Image Processing","theory":3,"practical":1},
  {"name":"Embedded Systems and IoMT","theory":3,"practical":1},
  {"name":"Bio Control Systems","theory":3,"practical":0},
  {"name":"Biomechanics","theory":3,"practical":0},
  {"name":"Sensors and Measurements","theory":2,"practical":1},
  {"name":"Foundation Skills in Integrated Product Development","theory":3,"practical":0},
  {"name":"Medical Device Design","theory":3,"practical":0},
  {"name":"Medical Device Regulations","theory":3,"practical":0},
  {"name":"Patient Safety, Standards and Ethics","theory":3,"practical":0},
  {"name":"Medical Innovation and Entrepreneurship","theory":3,"practical":0},
  {"name":"Rapid Prototyping","theory":3,"practical":0},
  {"name":"Clinical Engineering","theory":3,"practical":0},
  {"name":"Hospital Planning and Management","theory":3,"practical":0},
  {"name":"Medical Waste Management","theory":3,"practical":0},
  {"name":"Economics and Management for Engineers","theory":3,"practical":0},
  {"name":"Biostatistics","theory":3,"practical":0},
  {"name":"Forensic Science in Healthcare","theory":3,"practical":0},
  {"name":"Virtual Reality and Augmented Reality in Health care","theory":2,"practical":1},
  {"name":"Virtual Instrumentation for Clinical Applications","theory":3,"practical":1},
  {"name":"Brain Computer Interface and its Applications","theory":2,"practical":1},
  {"name":"Medical Nanotechnology","theory":3,"practical":0},
  {"name":"Medical Informatics","theory":3,"practical":0},
  {"name":"Robotics in Medicine","theory":3,"practical":0},
  {"name":"Ergonomics","theory":3,"practical":0},
  {"name":"Biofluids and Dynamics","theory":3,"practical":0},
  {"name":"BioMEMS","theory":2,"practical":1},
  {"name":"Haptics","theory":3,"practical":0},
  {"name":"Physiological Modeling","theory":3,"practical":0},
  {"name":"Rehabilitation Engineering","theory":3,"practical":0},
  {"name":"Technical Writing","theory":3,"practical":0},
  {"name":"Public Speaking","theory":0,"practical":3},
  {"name":"Communicative English","theory":3,"practical":1},
  {"name":"Basic Financial Accounting","theory":3,"practical":0},
  {"name":"Human Resource Management and Team Building","theory":3,"practical":0},
  {"name":"Stock Market and Company Operations","theory":3,"practical":0},
  {"name":"Probability and Queueing Models","theory":3,"practical":1},
  {"name":"Logic and Combinatorics","theory":4,"practical":0},
  {"name":"Algebra and Number Theory","theory":4,"practical":0},
  {"name":"Physics for Quantum Computing","theory":2,"practical":1},
  {"name":"Principles of Chemistry in Engineering","theory":3,"practical":1},
  {"name":"Engineering Design and Modelling","theory":0,"practical":3},
  {"name":"Basic Electrical, Electronics and Measurement Engineering","theory":2,"practical":1},
  {"name":"Programming Microcontrollers","theory":2,"practical":1},
  {"name":"Computer Architecture","theory":3,"practical":0},
  {"name":"Fundamentals of Web Application Development","theory":3,"practical":2},
  {"name":"Mobile User Interface Development","theory":2,"practical":1},
  {"name":"Programming Mobile Devices","theory":2,"practical":1},
  {"name":"Cloud Computing","theory":3,"practical":1},
  {"name":"Web Server Programming","theory":2,"practical":1},
  {"name":"Advanced Java Web Applications","theory":2,"practical":1},
  {"name":"Cloud Native App Development","theory":2,"practical":1},
  {"name":"Modern Web Application Development","theory":2,"practical":1},
  {"name":"Introduction to IoT","theory":2,"practical":1},
  {"name":"Operating System","theory":3,"practical":1},
  {"name":"Computer Networks","theory":3,"practical":1},
  {"name":"Theory of Computation","theory":3,"practical":0},
  {"name":"Software Engineering","theory":3,"practical":1},
  {"name":"Cryptography","theory":2,"practical":1},
  {"name":"Engineering Mechanics and Product Development","theory":2,"practical":1},
  {"name":"Object Oriented Programming using C#","theory":2,"practical":1},
  {"name":"Introduction to Data Science","theory":2,"practical":1},
  {"name":"Digital Image Processing Techniques","theory":2,"practical":1},
  {"name":"Parallel Computing Architecture","theory":3,"practical":1},
  {"name":"Applied Artificial Intelligence","theory":2,"practical":1},
  {"name":"Neural Networks","theory":2,"practical":1},
  {"name":"Web Data Mining","theory":3,"practical":1},
  {"name":"Deep Learning and its Applications","theory":2,"practical":1},
  {"name":"Applications of Artificial Intelligence","theory":2,"practical":1},
  {"name":"Applied Natural Language Processing","theory":2,"practical":1},
  {"name":"Computer Vision","theory":2,"practical":1},
  {"name":"Mobile Robotics","theory":2,"practical":1},
  {"name":"Reinforcement Learning","theory":2,"practical":1},
  {"name":"Speech Analysis and Processing","theory":2,"practical":1},
  {"name":"Special Topics in Artificial Intelligence","theory":2,"practical":1},
  {"name":"Concepts of Virtual And Augmented Reality","theory":2,"practical":1},
  {"name":"Mobile VR And AI In Unity","theory":2,"practical":1},
  {"name":"Scientific and Engineering Data Visualization","theory":2,"practical":1},
  {"name":"NoSQL Database Design","theory":2,"practical":1},
  {"name":"Game Programming","theory":2,"practical":2},
  {"name":"Self Driving Car","theory":2,"practical":2},
  {"name":"Smart Manufacturing Technology","theory":2,"practical":1},
  {"name":"Big Data Analytics","theory":3,"practical":0},
  {"name":"Business Analytics","theory":2,"practical":1},
  {"name":"Cognitive Systems","theory":3,"practical":0},
  {"name":"Distributed Database","theory":3,"practical":0},
  {"name":"Data Mining and Warehousing","theory":2,"practical":1},
  {"name":"Expert Systems","theory":3,"practical":0},
  {"name":"Knowledge Engineering","theory":3,"practical":0},
  {"name":"Mobile Database","theory":3,"practical":0},
  {"name":"Multimedia Database","theory":3,"practical":0},
  {"name":"Video Processing","theory":2,"practical":1},
  {"name":"Information Security and Access Control","theory":2,"practical":1},
  {"name":"Security Assessment and Risk Analysis","theory":3,"practical":1},
  {"name":"Advanced Graph Theory and Applications","theory":2,"practical":1},
  {"name":"Advanced Data Structures","theory":2,"practical":1},
  {"name":"Control of Robotic Systems","theory":2,"practical":1},
  {"name":"Cryptography and Security","theory":2,"practical":1},
  {"name":"Information Theory for Cyber Security","theory":2,"practical":1},
  {"name":"Introduction to Robotics","theory":2,"practical":1},
  {"name":"Kinematics and Dynamics of Robots","theory":2,"practical":1},
  {"name":"Robotic Sensors","theory":2,"practical":1},
  {"name":"Steganography and Digital Watermarking","theory":2,"practical":1},
  {"name":"Computer Graphics for Virtual Reality","theory":2,"practical":1},
  {"name":"Mathematical Modelling and Computer Aided Engineering","theory":2,"practical":1},
  {"name":"Agile Software Development","theory":3,"practical":1},
  {"name":"Software Testing","theory":2,"practical":1},
  {"name":"Virtualization and Containerization","theory":2,"practical":1},
  {"name":"Blockchain for Business","theory":2,"practical":1},
  {"name":"Robot Programming","theory":2,"practical":1},
  {"name":"Drone Assembly and Applications","theory":2,"practical":1},
  {"name":"Artificial Intelligence for Games","theory":2,"practical":1},
  {"name":"Drone Design and Control","theory":2,"practical":1},
  {"name":"Web Application User Interface Development","theory":2,"practical":1},
  {"name":"Fundamentals of Large Language Models","theory":2,"practical":1},
  {"name":"Exploratory Data Analysis","theory":2,"practical":1},
  {"name":"Recommender Systems","theory":2,"practical":1},
  {"name":"Neural Networks and Deep Learning","theory":2,"practical":1},
  {"name":"Text and Speech Analysis","theory":2,"practical":1},
  {"name":"Image and Video Analytics","theory":2,"practical":1},
  {"name":"Augmented Reality and ARCore","theory":2,"practical":1},
  {"name":"Extended Reality","theory":2,"practical":1},
  {"name":"Time Series Analysis and Forecasting","theory":3,"practical":1},
  {"name":"Blockchain and Cryptocurrency","theory":3,"practical":0},
  {"name":"Cyber Forensics","theory":3,"practical":0},
  {"name":"Machine Learning for Bioinformatics","theory":3,"practical":0},
  {"name":"Genetic Algorithms","theory":2,"practical":1},
  {"name":"Data Modeling","theory":3,"practical":0},
  {"name":"Brain Computer Interaction","theory":3,"practical":0},
  {"name":"Statistical Learning Theory","theory":2,"practical":1},
  {"name":"Sensors and Actuators for IoT","theory":2,"practical":1},
  {"name":"Security and Trust in IoT","theory":2,"practical":1},
  {"name":"Industrial Internet of Things","theory":2,"practical":1},
  {"name":"Software for Embedded Systems","theory":2,"practical":1},
  {"name":"IoT Architecture and Protocols","theory":3,"practical":0},
  {"name":"Arduino for IoT","theory":2,"practical":1},
  {"name":"Raspberry Pi for IoT","theory":2,"practical":1},
  {"name":"Motion Planning Techniques","theory":2,"practical":1},
  {"name":"Advanced Java Programming","theory":2,"practical":1},
  {"name":"Python Programming for IoT","theory":3,"practical":0},
  {"name":"Applications of IoT in Robotics","theory":3,"practical":0},
  {"name":"Programming for IoT Boards","theory":3,"practical":0},
  {"name":"Design of Smart Cities","theory":3,"practical":0},
  {"name":"IoT and Multimedia Technology","theory":3,"practical":0},
  {"name":"Mobile Application Development for IoT","theory":3,"practical":0},
  {"name":"Open Source Programming for IoT","theory":3,"practical":0},
  {"name":"Compiler Design","theory":3,"practical":1},
  {"name":"Cloud Security","theory":2,"practical":1},
  {"name":"Ethical Hacking Techniques","theory":2,"practical":1},
  {"name":"Cyber Law and Compliance","theory":3,"practical":0},
  {"name":"Digital Forensics and Digital Investigations","theory":2,"practical":1},
  {"name":"Prototyping of IoT Systems","theory":2,"practical":1},
  {"name":"Edge Computing","theory":2,"practical":1},
  {"name":"Security for IoT Systems","theory":3,"practical":0},
  {"name":"Computer Graphics and Multimedia","theory":3,"practical":0},
  {"name":"Software Project Management","theory":3,"practical":0},
  {"name":"Service Oriented Architecture","theory":3,"practical":0},
  {"name":"Multicore Architecture","theory":3,"practical":0},
  {"name":"Human Computer Interaction","theory":3,"practical":0},
  {"name":"Parallel and Distributed Systems","theory":3,"practical":0},
  {"name":"Social Network Analysis","theory":3,"practical":0},
  {"name":"Soft Computing","theory":3,"practical":0},
  {"name":"Green Computing","theory":3,"practical":0},
  {"name":"Network Management Systems","theory":3,"practical":0},
  {"name":"Block Chain Architecture and its Use Cases","theory":3,"practical":0},
  {"name":"Software Testing and Quality Assurance","theory":3,"practical":0},
  {"name":"Mobile Computing","theory":3,"practical":0},
  {"name":"Game Design and Development","theory":3,"practical":0},
  {"name":"Data Science","theory":3,"practical":0},
  {"name":"Data Warehousing and Data Mining","theory":3,"practical":0},
  {"name":"Advanced Database Management System","theory":3,"practical":1},
  {"name":"Information Retrieval","theory":3,"practical":0},
  {"name":"Deep Learning","theory":3,"practical":0},
  {"name":"R Programming","theory":2,"practical":1},
  {"name":"Robotics and its Applications","theory":3,"practical":0},
  {"name":"Quantum Computing","theory":3,"practical":0},
  {"name":"Cyber Security","theory":3,"practical":0},
  {"name":"Virtual Reality","theory":3,"practical":0},
  {"name":"Information Security Intelligence and Analytics using Big Data","theory":2,"practical":1},
  {"name":"Prevention Methodology for Cybersecurity","theory":2,"practical":1},
  {"name":"Trusted Network Systems","theory":3,"practical":0},
  {"name":"Firewalls and Intrusion Detection System","theory":2,"practical":1},
  {"name":"Secure Software Engineering","theory":2,"practical":1},
  {"name":"System Security","theory":3,"practical":0},
  {"name":"Hardware Security","theory":3,"practical":0},
  {"name":"Fog Computing","theory":3,"practical":0},
  {"name":"Realtime Operating System","theory":2,"practical":1},
  {"name":"Open Source Operating System","theory":2,"practical":1},
  {"name":"Kernel Programming","theory":2,"practical":1},
  {"name":"Fundamentals of Cryptocurrency","theory":3,"practical":0},
  {"name":"Cloud Services Management","theory":2,"practical":1},
  {"name":"UI and UX Design","theory":2,"practical":1},
  {"name":"AI and Ethics","theory":3,"practical":0},
  {"name":"Software Testing and Automation","theory":2,"practical":1},
  {"name":"DevOps","theory":2,"practical":1},
  {"name":"Web Application Security","theory":2,"practical":1},
  {"name":"Stream Processing","theory":2,"practical":1},
  {"name":"Core Computing Concepts","theory":2,"practical":1},
  {"name":"Data Privacy and Protection","theory":2,"practical":1},
  {"name":"Blockchain Platforms and Its Use Cases","theory":2,"practical":1},
  {"name":"Smart Contract and Solidity","theory":2,"practical":1},
  {"name":"Blockchain and Fintech","theory":2,"practical":1},
  {"name":"Public Key Infrastructure and Trust Management","theory":2,"practical":1},
  {"name":"Bitcoin Mining","theory":2,"practical":1},
  {"name":"Robotic Process Automation","theory":2,"practical":1},
  {"name":"Software Project Management and Version Control","theory":3,"practical":0},
  {"name":"Generative AI Application Development","theory":2,"practical":1},
  {"name":"Fine Tuning Large Language Models","theory":3,"practical":0},
  {"name":"Applied Data Science","theory":2,"practical":1},
  {"name":"Entrepreneurship and Small Business Development","theory":2,"practical":1},
  {"name":"Software Development and Operations","theory":3,"practical":0},
  {"name":"Serverless App Development","theory":3,"practical":0},
  {"name":"Enterprise Cloud Architecture","theory":3,"practical":0},
  {"name":"Low-Code App Development","theory":3,"practical":0},
  {"name":"Cloud System Administration","theory":3,"practical":0},
  {"name":"Machine Learning Operations","theory":3,"practical":0},
  {"name":"Grid and Cloud Computing","theory":3,"practical":1},
  {"name":"Distributed Computing","theory":3,"practical":0},
  {"name":"Information Theory and Coding Techniques","theory":3,"practical":0},
  {"name":"Enterprise Resource Planning","theory":3,"practical":0},
  {"name":"User Interface Design","theory":3,"practical":0},
  {"name":"Information Storage Management","theory":3,"practical":0},
  {"name":"Software Design Patterns","theory":3,"practical":0},
  {"name":"E-Learning Techniques","theory":3,"practical":0},
  {"name":"TCP/IP Design and Implementation","theory":3,"practical":0},
  {"name":"Advanced Algorithms","theory":3,"practical":0},
  {"name":"Ethical Hacking","theory":3,"practical":0},
  {"name":"DHTML and XML","theory":3,"practical":0},
  {"name":"E-Commerce","theory":3,"practical":0},
  {"name":"Free Open Source Software","theory":3,"practical":0},
  {"name":"Software Agents","theory":3,"practical":0},
  {"name":"Business Intelligence and Analytics","theory":3,"practical":0},
  {"name":"Mathematics for Artificial Intelligence","theory":4,"practical":0},
  {"name":"Transforms and Its Applications","theory":4,"practical":0},
  {"name":"Linear Algebra Laboratory","theory":0,"practical":2},
  {"name":"Fundamentals of Artificial Intelligence","theory":2,"practical":1},
  {"name":"Big Data Mining and Analysis","theory":2,"practical":1},
  {"name":"Machine Learning","theory":3,"practical":0},
  {"name":"Mobile Application Development","theory":1,"practical":2},
  {"name":"Ad Hoc and Wireless Sensor Networks","theory":3,"practical":0},
];

export function searchSubjects(query: string): SubjectSuggestion[] {
  if (!query || query.length < 2) return [];
  const q = query.toLowerCase();
  return SUBJECTS_DB.filter(s => s.name.toLowerCase().includes(q)).slice(0, 8);
}
